### ISSUE TITLE
Duplicate type name within an assembly

### ISSUE THREAD

**Issue by tflinkow** [flinkow/fluentmvvm#5]
Trying to build two instances with different generic types (e.g. `int` and `string`) leads to a `Duplicate type name within an assembly` exception.

### Stack trace:

```
   at System.Reflection.Emit.ModuleBuilder.CheckTypeNameConflict(String strTypeName, Type enclosingType)
   at System.Reflection.Emit.AssemblyBuilderData.CheckTypeNameConflict(String strTypeName, TypeBuilder enclosingType)
   at System.Reflection.Emit.TypeBuilder..ctor(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType)
   at System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr)
   at FluentMvvm.Emit.BackingFieldProvider.BuildForType(Type targetType) in C:\devel\fluentmvvm\fluentmvvm\Emit\BackingFieldProvider.cs:line 132
   at FluentMvvm.Emit.BackingFieldProvider.Get(Type targetType) in C:\devel\fluentmvvm\fluentmvvm\Emit\BackingFieldProvider.cs:line 90
   at FluentMvvm.FluentViewModelBase..ctor() in C:\devel\fluentmvvm\fluentmvvm\FluentViewModelBase.cs:line 38
```

### How to reproduce:

```csharp
public class Generic<T> : FluentViewModelBase
{
  public T Foo { get; set; }
}

public class Program
{
  public static void Main(string[] args)
  {
    new Generic<int>();
    new Generic<string>();
  }
}
```

**Comment by tflinkow** [comment]
Fixed in https://github.com/flinkow/fluentmvvm/commit/76339d9e85d12e5845f32722aff1acfd4ddca604
